export const routes = {
  home: "/",
  residential: "/residential",
  commercial: "/commercial",
  commercialPartnerships: "/commercial-partnerships",
  services: "/services",
  service: (slug: string) => "/services/" + slug,
  commercialService: "/services/commercial",
  industrialFacilities: "/services/industrial",
  industries: "/industries",
  industry: (slug: string) => "/industries/" + slug,
  serviceArea: "/service-area",
  location: (slug: string) => "/service-area/" + slug,
  about: "/about",
  reviews: "/reviews",
  contact: "/contact",
  requestService: "/request-service",
  troubleshoot: "/troubleshoot",
  financing: "/financing",
  privacy: "/privacy-policy",
  terms: "/terms",
} as const;
